# Use postgres/example user/password credentials
version: '3.1'
name: d-composes
services:

  postgres-db:
    container_name: postgres-db
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nopass@!23
    ports:
      - "5432:5432"
    volumes:
      - /media/raiyan/BNDA/_docker-postgre-vol.data:/var/lib/postgre.data

  adminer:
    container_name: db-adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080